# IBM Developer's Workframe/2 Make File Creation run at 12:29:23 on 04/08/92

# Make File Creation run in directory:
#   E:\C\SHEET;

# Assumed INCLUDE environment variable path:
#   D:\IBMC\INCLUDE;
#   D:\TOOLKT20\C\OS2H;
#   D:\TOOLKT20\ASM\OS2INC;
#   E:\C\INCLUDE;


PRESENT.RES:  PRESENT.RC  \
#  {.;$(INCLUDE)}OS2.H  \
   {.;$(INCLUDE)}PRESENT.H  \
   PRESENT.ICO  \
   PRESENT.PTR  \
   MAKEFILE

PRESENT.OBJ:  PRESENT.C  \
#  {.;$(INCLUDE);}os2.h  \
#  {.;$(INCLUDE);}stdio.h  \
#  {.;$(INCLUDE);}stdlib.h  \
#  {.;$(INCLUDE);}string.h  \
#  {.;$(INCLUDE);}malloc.h  \
   {.;.;$(INCLUDE);}presfont.h  \
   {.;.;$(INCLUDE);}present.h  \
   MAKEFILE

PRESFONT.OBJ:  PRESFONT.C  \
#  {.;$(INCLUDE);}os2.h  \
   {.;$(INCLUDE);}presfont.h  \
#  {.;$(INCLUDE);}stdio.h  \
#  {.;$(INCLUDE);}stdlib.h  \
#  {.;$(INCLUDE);}string.h  \
   MAKEFILE
